[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "model_apps"
version = "0.1.0"
description = "Extension module for API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "Django",
  "djangorestframework",
  "django-filter",
  "django-simple-history",
  "drf-spectacular",
  "faker",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]